Imports System

Namespace SimsLib.IFF
    Public Class BHAVStrings
        ' Fields
        Public Shared BHAVString139 As String() = New String() { "sleep", "generic sims call", "expression", "find best interaction", "grab", "drop", "change suit/accessory", "refresh", "random number", "burn", "tutorial", "get distance to", "get direction to", "push interaction", "find best object for function", "tree break point", "find location for", "idle for input", "remove object instance", "make new character", "run functional tree", "show string (UNUSED)", "look towards", "play sound event", "old relationship (DEPRECATED)", "alter budget", "relationship", "go to relative position", "run tree by name", "set motive change", "gosub found action", "set to next", "test object type", "find five worst motives", "UI effect", "special effect", "dialog", "test sim interacting with", "unused", "unused", "unused", "set balloon/headline", "create new object instance", "drop onto", "animate sim", "go to routing slot", "snap", "reach", "stop ALL sounds", "notify the stack object out of idle", "add/change the action string", "manage inventory[HD, animate object in TSO]", "change light color[TSO]", "change sun color[TSO]", "point light at object[TSO]", "sync field[TSO]", "ownership[TSO]", "start persistant dialog[TSO]", "end persistant dialog[TSO]", "update persistant dialog[TSO]", "poll persistant dialog[TSO]", "~unused[TSO]", "invoke plugin[TSO]", "get terrain info[TSO]" }
        Public Shared BHAVString153 As String() = New String() { "my", "stack obj's", "target's [OBSOLETE]" }
        Public Shared BHAVString201Obj As String() = New String() { "preparing food", "cooking food", "flat surface", "disposing", "eating", "picking up from slot", "washing dish", "eating surface", "siting", "standing", "serving surface", "cleaning", "gardening", "washing hands", "repairing", "sleeping[V]" }
        Public Shared BHAVString201Run As String() = New String() { "prepare food", "cook food", "put on flat surface", "dispose", "eat", "pick up from slot", "wash dish", "put on eating surface", "sit", "stand", "put on serving surface", "clean", "garden", "wash hands", "repair", "sleep[V]" }
        Public Shared BHAVString212 As String() = New String() { "graphic", "lighting contribution", "room score contribution" }
        Public Shared BHAVString220 As String() = New String() { "house tutorial complete", "swap my and stack obj's slots[HD]", "set action icon to stack obj", "pull down taxi dialog[HD]", "add stack obj to family", "take assets of family in temp 0", "remove stack obj from family", "DEPRECATED - make new neighbor", "family tutorial complete", "architecture tutorial complete", "disable build and buy", "enable build and buy", "temp 0 := distance to camera", "abort interactions with stack obj", "house radio station := temp 0", "my footprint extension := temp 0", "change normal outfit to next available", "change to lot in temp 0[HD]", "build the downtown Sim and place obj ID in temp 0[HD]", "spawn downtown date of person in temp 0; place spawned autofollow Sim in temp 0[HD]", "spawn take back home date of person in temp 0; place spawned autofollow Sim in temp 0[HD]", "spawn inventory SimData effects[HD]", "select downtown lot[HD]", "get downtown time from SO's inventory(Hours in T0, Minutes in T1)[HD]", "change suits permanently[HD]", "save this Sim's persistent data[HD]", "build vacation family; temp 0 := family number[V]", "temp 0 :=  number of available vacation lots[V]", "temp 0 := temp[0]'s lot's zoning type[U]", "set stack obj's suit: type := temp[0], index := temp[1]; temp[1] := old index[U]", "get stack obj's suit: temp[0] := type. temp[1] := index[U]", "temp[1] := count stack obj's suits of type temp[0][U]", "create all purchased pets near owner[U]", "add to family in temp 0[U]" }
        Public Shared BHAVString221 As String() = New String() { "person instance ID", "belongs in house", "person age", "relationship raw score", "relationship score", "friend count", "house number", "has telephone", "has baby", "family friend count" }
        Public Shared BHAVString222 As String() = New String() { "run in my stack", "run in stack obj's stack", "push onto my stack" }
        Public Shared BHAVString223 As String() = New String() { "inherited", "max", "autonomous", "user" }
        Public Shared BHAVString224 As String() = New String() { "inherited", "max", "autonomous", "user" }
        Public Shared BHAVString231 As String() = New String() { "stack obj", "tile in front of stack obj", "floor under stack obj" }
        Public Shared BHAVString239 As String() = New String() { "normal", "out-of-world", "smoke", "object vector", "lateral", "random[HD]" }
    End Class
End Namespace

